### ISSUE TITLE
Refactor opcodes

### ISSUE THREAD

**Issue by franticspider** [uoy-research/stringmol#4]
Create a new file `opcodes.cpp` that contains *all* the opcodes used in a reaction. Refactor for various flavours where possible

## Tidy up individual opcodes

 - [ ] **`speig_hcopy`** differs only slightly from `OpcodeCopy` - but where? Can it be refactored?

## Tidy up associated functions

- [x] #30
- [x] **`AgentRewindDanglingPtrs`** only called after a Cleave (stringPM.cpp) see #30
- [x] **`AgentCheckZeroLengthString`** only(?) called after a Cleave (stringPM.cpp) see #30
- [x] **`stringPM::ReactionExecuteOpcode`** - could this be any neater? (stringPM.cpp) *have made each opcode have a function even if v. simple*; Still some work to do on this possibly...  

## Tidy up non-vanilla calls to opcodes

- [x] **`stringPM::ReactionExecuteOpcode_Comass`** - where is this different to stringPM::ReactionExecuteOpcode? Could this drive some tidying? 
- [x] #32
- [x] #33
- [x] **`ReactionExecuteOpcode_Spatial`** - where is this different to stringPM::ReactionExecuteOpcode? Could this drive some tidying? (setupSM.cpp) *Kept in approximate alignment with other versions, but the remainder will be easer when #24 has been done*

**Comment by franticspider** [comment]
Got smoke test for comass working so we can check refactor of **`stringPM::comass_ReactionExecuteOpcode`**

**Comment by franticspider** [comment]
Decided that we need to write a test for `OpcodeCopy` function and it's "conservation of mass" variant. This started a bit of a rabbit-hole, because to write this cleanly we need a good way of setting up a reaction between two agents, that had to be made from strings.... Steps so far have been:

 
- [x] made `agents.cpp` file work (found a naming error in `agents_base` that was causing a complex bug)
- [x] need to remove `SpeciesListUpdate` from the `AgentUnbind` function, to separate out "agent" code from "species" code
